# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
    zookeeper:
        image: zookeeper:latest

    dubbo-samples-rpccontext-provider2:
        type: app
        basedir: dubbo-samples-rpccontext-provider2
        mainClass: org.apache.dubbo.samples.rpccontext.RpcContextProvider2
        systemProps:
            - zookeeper.address=zookeeper
        waitPortsBeforeRun:
            - zookeeper:2181
        checkPorts:
            - 20882
        checkLog: "Rpc context provider2 started"
        depends_on:
            - zookeeper


    dubbo-samples-rpccontext-provider:
        type: app
        basedir: dubbo-samples-rpccontext-provider1
        mainClass: org.apache.dubbo.samples.rpccontext.RpcContextProvider1
        systemProps:
            - zookeeper.address=zookeeper
        waitPortsBeforeRun:
            - zookeeper:2181
        checkPorts:
            - 20880
        checkLog: "Rpc context provider1 started"
        depends_on:
            - zookeeper
            - dubbo-samples-rpccontext-provider2

    dubbo-samples-rpccontext-consumer:
        type: test
        basedir: dubbo-samples-rpccontext-consumer
        tests:
            - "**/*IT.class"
        systemProps:
            - zookeeper.address=zookeeper
        waitPortsBeforeRun:
            - zookeeper:2181
            - dubbo-samples-rpccontext-provider:20880
            - dubbo-samples-rpccontext-provider2:20882
        depends_on:
            - zookeeper
            - dubbo-samples-rpccontext-provider
            - dubbo-samples-rpccontext-provider2
