apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-samples-mesh-consumer
  namespace: dubbo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-samples-mesh-consumer
  template:
    metadata:
      labels:
        app: dubbo-samples-mesh-consumer
    spec:
      serviceAccountName: dubbo-sa
      containers:
        - name: server
          image: dubboteam/dubbo-samples-mesh-consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 20880
              protocol: TCP
            - containerPort: 22222
              protocol: TCP
            - containerPort: 31000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: 22222
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 22222
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /startup
              port: 22222
            failureThreshold: 30
            periodSeconds: 10