apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-samples-mesh-provider
  namespace: dubbo-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dubbo-samples-mesh-provider
  template:
    metadata:
      labels:
        app: dubbo-samples-mesh-provider
    #      annotations:
    #        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      serviceAccountName: dubbo-sa
      containers:
        - name: server
          image: dubboteam/dubbo-samples-mesh-provider
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
              protocol: TCP
            - containerPort: 22222
              protocol: TCP
            - containerPort: 31000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: 22222
            #            grpc:
            #              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 22222
            #            grpc:
            #              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
          startupProbe:
            httpGet:
              path: /startup
              port: 22222
            #            grpc:
            #              port: 50052
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 30