# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  zookeeper:
    image: zookeeper:latest

  dubbo-samples-applevel-override1:
    type: app
    basedir: .
    mainClass: org.apache.dubbo.samples.governance.BasicProvider
    systemProps:
      - zookeeper.address=zookeeper
      - zookeeper.port=2181
      - dubbo.port=20880
    waitPortsBeforeRun:
      - zookeeper:2181
    checkPorts:
      - 20880
    checkLog: "dubbo service started"
    depends_on:
      - zookeeper

  dubbo-samples-applevel-override2:
    type: app
    basedir: .
    mainClass: org.apache.dubbo.samples.governance.BasicProvider
    systemProps:
      - zookeeper.address=zookeeper
      - zookeeper.port=2181
      - dubbo.port=20881
    waitPortsBeforeRun:
      - zookeeper:2181
    checkPorts:
      - 20881
    checkLog: "dubbo service started"
    depends_on:
      - zookeeper

  dubbo-samples-applevel-override-test:
    type: test
    basedir: .
    tests:
      - "**/*IT.class"
    systemProps:
      - zookeeper.address=zookeeper
      - zookeeper.port=2181
    waitPortsBeforeRun:
      - zookeeper:2181
      - dubbo-samples-applevel-override1:20880
      - dubbo-samples-applevel-override2:20881
    depends_on:
      - zookeeper
      - dubbo-samples-applevel-override1
      - dubbo-samples-applevel-override2

